grub-efi bbappend: fix grub warning
While ostree enabled, a grub warning is reported
...
error: no such device: ((hd0,gpt1)/EFI/BOOT)/EFI/BOOT/grub.cfg.
...

By default, root = (hd0,gpt1), do not need to set it through search.file
if ostree is enabled

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>