lat installer: enter a shell if install failed
If install failed, enter a shell other than reboot which is more
friendly for user

...
Caught error, waiting for outstanding tasks
error: Writing content object: min-free-space-percent '3%' would be exceeded, at least 1.7?MB requested
Error: ostree pull failed

Save install-fail-230508-065635.log to partition /dev/sda1
Save install-fail-230508-065635.log to partition /dev/vda1
Install failed, starting boot shell.  System will reboot on exit
You can execute the install with verbose message:
     INSTSH=0 bash -v -x /install
bash-5.1#
...

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>