meta-lat: fix error about importing GPG key
Fix the error:
ERROR: initramfs-ostree-image-1.0-r0 do_rootfs:
 Could not import GPG key for ostree signing:
gpg: key CFA856DFC7CB87BE: public key "Wind-River-Linux-Sample (RPM Signing Certificate) <svc-linux@gmail.com>" imported
gpg: key CFA856DFC7CB87BE/CFA856DFC7CB87BE: error sending to agent: End of file
gpg: error reading '....../layers/wrlinux/wrlinux-distro/files/sample-keys/rpm_keys/RPM-GPG-PRIVKEY-Wind-River-Linux-Sample': End of file
gpg: import from '....../layers/wrlinux/wrlinux-distro/files/sample-keys/rpm_keys/RPM-GPG-PRIVKEY-Wind-River-Linux-Sample' failed: End of file

This is caused by PSEUDO issue, and can be solved by set GPG_PATH
into PSEUDO_IGNORE_PATHS and config a proper path for GPG_PATH in
local.conf.

Signed-off-by: Li Zhou <li.zhou@windriver.com>